version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "80:3000"
    environment:
      - REACT_APP_API_URL=http://${EC2_PUBLIC_IP}:8081

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8081:5000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - CORS_ORIGIN=http://${EC2_PUBLIC_IP}

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: