version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - "443:3000"
    environment:
      - REACT_APP_API_URL=https://${EC2_PUBLIC_IP}:5000
    depends_on:
      - backend
    volumes:
      - ./ssl:/app/ssl:ro

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - CORS_ORIGIN=https://${EC2_PUBLIC_IP}:443
    depends_on:
      - mongo
    volumes:
      - ./ssl:/app/ssl:ro

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: